export interface AffiliateLeaderboardInfluencer {
  id: string;
  rank: number;
  name: string;
  stageName: string;
  username: string;
  avatar: string;
  verified: boolean;
  socialNetwork: "youtube" | "tiktok" | "instagram" | "twitch" | "kwai";
  channelUrl: string;
  audience: string;
  topGameId: string;
  topGameName: string;
  topGameCategory: string;
  topGameEmoji: string;
  topGameColor: string;
  totalWithdrawnPix: number;
  weeklyWithdrawnPix: number;
  monthlyWithdrawnPix: number;
  totalLeads: number;
  weeklyLeads: number;
  conversionRate: string;
  badgeTitle: string;
  activeCampaigns: number;
  streakWeeks: number;
  recentPixWithdrawal: {
    amount: number;
    timeAgo: string;
  };
}

export const SIMULATED_AFFILIATE_INFLUENCERS: AffiliateLeaderboardInfluencer[] = [
  {
    id: "inf-1",
    rank: 1,
    name: "Felipe Santos",
    stageName: "Nobru Games",
    username: "felipe_nobru",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "youtube",
    channelUrl: "https://youtube.com/@felipe_nobru",
    audience: "2.4M inscritos",
    topGameId: "game-fruit-cash",
    topGameName: "Fruit Cash",
    topGameCategory: "Habilidade",
    topGameEmoji: "🍓",
    topGameColor: "#22c55e",
    totalWithdrawnPix: 28750.0,
    weeklyWithdrawnPix: 8450.0,
    monthlyWithdrawnPix: 21900.0,
    totalLeads: 1842,
    weeklyLeads: 412,
    conversionRate: "18.4%",
    badgeTitle: "👑 Top 1 Afiliado Geral",
    activeCampaigns: 4,
    streakWeeks: 9,
    recentPixWithdrawal: {
      amount: 1500.0,
      timeAgo: "há 14 min",
    },
  },
  {
    id: "inf-2",
    rank: 2,
    name: "Camila Silva",
    stageName: "Camila Mih",
    username: "camilagames_ofc",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "tiktok",
    channelUrl: "https://tiktok.com/@camilagames_ofc",
    audience: "1.3M seguidores",
    topGameId: "game-krs-777",
    topGameName: "KRS 777 (Casino Online)",
    topGameCategory: "Cassino",
    topGameEmoji: "🎰",
    topGameColor: "#fbbf24",
    totalWithdrawnPix: 21420.0,
    weeklyWithdrawnPix: 6150.0,
    monthlyWithdrawnPix: 17200.0,
    totalLeads: 1390,
    weeklyLeads: 320,
    conversionRate: "16.2%",
    badgeTitle: "🥈 Rainha dos Slots",
    activeCampaigns: 3,
    streakWeeks: 7,
    recentPixWithdrawal: {
      amount: 2200.0,
      timeAgo: "há 42 min",
    },
  },
  {
    id: "inf-3",
    rank: 3,
    name: "Rodrigo Almeida",
    stageName: "Dentinho Play",
    username: "rodrigo_playgames",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "instagram",
    channelUrl: "https://instagram.com/rodrigo_playgames",
    audience: "820k seguidores",
    topGameId: "game-blockerino",
    topGameName: "Blockerino",
    topGameCategory: "Puzzle",
    topGameEmoji: "🧩",
    topGameColor: "#00F0FF",
    totalWithdrawnPix: 16900.0,
    weeklyWithdrawnPix: 4800.0,
    monthlyWithdrawnPix: 13400.0,
    totalLeads: 1120,
    weeklyLeads: 275,
    conversionRate: "14.8%",
    badgeTitle: "🥉 Mestre do Blockerino",
    activeCampaigns: 4,
    streakWeeks: 6,
    recentPixWithdrawal: {
      amount: 950.0,
      timeAgo: "há 1h",
    },
  },
  {
    id: "inf-4",
    rank: 4,
    name: "Beatriz Rezende",
    stageName: "Biazinha Gamer",
    username: "biazinha_yt",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "youtube",
    channelUrl: "https://youtube.com/@biazinha_yt",
    audience: "650k inscritos",
    topGameId: "game-bubbles-cash",
    topGameName: "Bubble Cash",
    topGameCategory: "Habilidade",
    topGameEmoji: "🎯",
    topGameColor: "#a855f7",
    totalWithdrawnPix: 13450.0,
    weeklyWithdrawnPix: 3900.0,
    monthlyWithdrawnPix: 10800.0,
    totalLeads: 890,
    weeklyLeads: 195,
    conversionRate: "15.1%",
    badgeTitle: "🎯 Especialista em Torneios",
    activeCampaigns: 3,
    streakWeeks: 5,
    recentPixWithdrawal: {
      amount: 800.0,
      timeAgo: "há 2h",
    },
  },
  {
    id: "inf-5",
    rank: 5,
    name: "Thiago Oliveira",
    stageName: "TK Gameplays",
    username: "tk_gameplays",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "instagram",
    channelUrl: "https://instagram.com/tk_gameplays",
    audience: "490k seguidores",
    topGameId: "game-fruit-cash",
    topGameName: "Fruit Cash",
    topGameCategory: "Habilidade",
    topGameEmoji: "🍓",
    topGameColor: "#22c55e",
    totalWithdrawnPix: 10820.0,
    weeklyWithdrawnPix: 3100.0,
    monthlyWithdrawnPix: 8700.0,
    totalLeads: 740,
    weeklyLeads: 160,
    conversionRate: "13.7%",
    badgeTitle: "🍓 Cortador Lendário",
    activeCampaigns: 2,
    streakWeeks: 5,
    recentPixWithdrawal: {
      amount: 650.0,
      timeAgo: "há 3h",
    },
  },
  {
    id: "inf-6",
    rank: 6,
    name: "Larissa Mendes",
    stageName: "Lari Mendes",
    username: "lari_mendesgames",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "tiktok",
    channelUrl: "https://tiktok.com/@lari_mendesgames",
    audience: "380k seguidores",
    topGameId: "game-krs-777",
    topGameName: "KRS 777 (Casino Online)",
    topGameCategory: "Cassino",
    topGameEmoji: "🎰",
    topGameColor: "#fbbf24",
    totalWithdrawnPix: 8940.0,
    weeklyWithdrawnPix: 2450.0,
    monthlyWithdrawnPix: 6900.0,
    totalLeads: 610,
    weeklyLeads: 135,
    conversionRate: "12.9%",
    badgeTitle: "💎 VIP High Roller",
    activeCampaigns: 3,
    streakWeeks: 4,
    recentPixWithdrawal: {
      amount: 1100.0,
      timeAgo: "há 4h",
    },
  },
  {
    id: "inf-7",
    rank: 7,
    name: "Gabriel Santos",
    stageName: "Biel Play",
    username: "gabriel_play",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "twitch",
    channelUrl: "https://twitch.tv/gabriel_play",
    audience: "290k seguidores",
    topGameId: "game-blockerino",
    topGameName: "Blockerino",
    topGameCategory: "Puzzle",
    topGameEmoji: "🧩",
    topGameColor: "#00F0FF",
    totalWithdrawnPix: 7230.0,
    weeklyWithdrawnPix: 1980.0,
    monthlyWithdrawnPix: 5600.0,
    totalLeads: 480,
    weeklyLeads: 110,
    conversionRate: "11.5%",
    badgeTitle: "🧩 Quebra-Cabeças Pro",
    activeCampaigns: 2,
    streakWeeks: 3,
    recentPixWithdrawal: {
      amount: 450.0,
      timeAgo: "há 5h",
    },
  },
  {
    id: "inf-8",
    rank: 8,
    name: "Matheus Rocha",
    stageName: "Rocha Gamer",
    username: "rocha_games",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80",
    verified: true,
    socialNetwork: "youtube",
    channelUrl: "https://youtube.com/@rocha_games",
    audience: "240k inscritos",
    topGameId: "game-bubbles-cash",
    topGameName: "Bubble Cash",
    topGameCategory: "Habilidade",
    topGameEmoji: "🎯",
    topGameColor: "#a855f7",
    totalWithdrawnPix: 5890.0,
    weeklyWithdrawnPix: 1620.0,
    monthlyWithdrawnPix: 4500.0,
    totalLeads: 390,
    weeklyLeads: 92,
    conversionRate: "10.8%",
    badgeTitle: "⚡ Mira Precisa",
    activeCampaigns: 2,
    streakWeeks: 3,
    recentPixWithdrawal: {
      amount: 380.0,
      timeAgo: "há 6h",
    },
  },
  {
    id: "inf-9",
    rank: 9,
    name: "Lucas Silva",
    stageName: "Lucas PlayTV",
    username: "lucas_playtv",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80",
    verified: false,
    socialNetwork: "kwai",
    channelUrl: "https://kwai.com/@lucas_playtv",
    audience: "180k seguidores",
    topGameId: "game-fruit-cash",
    topGameName: "Fruit Cash",
    topGameCategory: "Habilidade",
    topGameEmoji: "🍓",
    topGameColor: "#22c55e",
    totalWithdrawnPix: 4750.0,
    weeklyWithdrawnPix: 1250.0,
    monthlyWithdrawnPix: 3600.0,
    totalLeads: 310,
    weeklyLeads: 78,
    conversionRate: "9.4%",
    badgeTitle: "🚀 Revelação da Semana",
    activeCampaigns: 1,
    streakWeeks: 2,
    recentPixWithdrawal: {
      amount: 300.0,
      timeAgo: "há 7h",
    },
  },
  {
    id: "inf-10",
    rank: 10,
    name: "Victor Shark",
    stageName: "Shark Gaming",
    username: "shark_gaming",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    verified: false,
    socialNetwork: "twitch",
    channelUrl: "https://twitch.tv/shark_gaming",
    audience: "150k seguidores",
    topGameId: "game-krs-777",
    topGameName: "KRS 777 (Casino Online)",
    topGameCategory: "Cassino",
    topGameEmoji: "🎰",
    topGameColor: "#fbbf24",
    totalWithdrawnPix: 3820.0,
    weeklyWithdrawnPix: 980.0,
    monthlyWithdrawnPix: 2900.0,
    totalLeads: 260,
    weeklyLeads: 65,
    conversionRate: "8.7%",
    badgeTitle: "🦈 Tubarão dos Ganhos",
    activeCampaigns: 2,
    streakWeeks: 2,
    recentPixWithdrawal: {
      amount: 250.0,
      timeAgo: "há 8h",
    },
  },
];

export const SIMULATED_AFFILIATE_ACTIVITIES = [
  {
    id: "act-1",
    influencerName: "Nobru Games",
    avatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&auto=format&fit=crop&q=80",
    action: "sacou via PIX instantâneo",
    amount: "R$ 1.500,00",
    game: "Fruit Cash 🍓",
    time: "há 14 min",
  },
  {
    id: "act-2",
    influencerName: "Camila Mih",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80",
    action: "gerou +18 novos leads qualificados",
    game: "KRS 777 Casino 🎰",
    time: "há 26 min",
  },
  {
    id: "act-3",
    influencerName: "Dentinho Play",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80",
    action: "bateu a meta de 1.100 leads",
    game: "Blockerino 🧩",
    time: "há 38 min",
  },
  {
    id: "act-4",
    influencerName: "Biazinha Gamer",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
    action: "sacou via PIX instantâneo",
    amount: "R$ 800,00",
    game: "Bubble Cash 🎯",
    time: "há 1h",
  },
  {
    id: "act-5",
    influencerName: "TK Gameplays",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80",
    action: "atingiu 740 cadastros ativos",
    game: "Fruit Cash 🍓",
    time: "há 2h",
  },
];
