import {
  Game,
  Campaign,
  LevelConfig,
  Badge,
  CreatorPassSeason,
  XPEventConfig,
  ScriptTemplate,
  CreativeAsset,
  PlatformSettings,
  CreatorProfile,
  CaptadorProfile,
  UserProfile,
  Submission,
  GameAffiliateStats,
  AffiliateConversionRecord,
} from "@/types";

export const SEED_GAMES: Game[] = [
  {
    id: "game-fruit-cash",
    name: "Fruit Cash",
    slug: "fruit-cash",
    logo_url: "https://fruitcash-fun.vercel.app/imagens/asset_2.png",
    thumbnail_url: "https://fruitcash-fun.vercel.app/imagens/og-banner.jpg",
    banner_url: "https://fruitcash-fun.vercel.app/imagens/og-banner.jpg",
    description: "O autêntico jogo da frutinha! Fatie frutas com reflexo afiado, desvie das bombas, acerte combos multiplicadores e receba saques imediatos via PIX.",
    how_it_works: "Fatie frutas com a ponta dos dedos na velocidade certa. Evite acertar bombas para não zerar sua sequência e ative combos épicos para multiplicar seus pontos e ganhos.",
    category: "Habilidade",
    tags: ["Habilidade", "Frutinha", "Reflexo", "Corte Rápido", "PIX Imediato"],
    primary_color: "#22c55e",
    play_url: "https://fruitcash-fun.vercel.app/",
    status: "active",
    campaigns_count: 1,
    created_at: "2026-08-01T10:00:00Z",
    updated_at: "2026-09-20T12:00:00Z",
  },
  {
    id: "game-krs-777",
    name: "KRS 777 (Casino Online)",
    slug: "krs-777",
    logo_url: "https://krs777.online/storage/krs777_favicon.png",
    thumbnail_url: "https://krs777.online/assets/images/krs777_share_banner.jpg",
    banner_url: "https://krs777.online/assets/images/krs777_share_banner.jpg",
    description: "Plataforma oficial de cassino online da KRS: Fortune Tiger, Fortune Ox, Mines e os slots mais disputados com bônus de boas-vindas e saques via PIX instantâneo.",
    how_it_works: "Lobby completo com centenas de slots premium, roletas e crash games. Depósitos a partir de R$ 20 com liberação via PIX na hora e suporte 24/7.",
    category: "Cassino",
    tags: ["Cassino", "Slots", "Fortune Tiger", "Mines", "PIX Imediato"],
    primary_color: "#fbbf24",
    play_url: "https://krs777.online/",
    status: "active",
    campaigns_count: 1,
    created_at: "2026-08-05T10:00:00Z",
    updated_at: "2026-09-21T14:00:00Z",
  },
  {
    id: "game-blockerino",
    name: "Blockerino",
    slug: "blockerino",
    logo_url: "https://blockerino-play.vercel.app/og.png",
    thumbnail_url: "https://blockerino-play.vercel.app/og.png",
    banner_url: "https://blockerino-play.vercel.app/og.png",
    description: "Desafio de raciocínio espacial e montagem de blocos em alta velocidade. Encaixe as peças no grid 10x10, complete linhas simultâneas e ative combos épicos!",
    how_it_works: "Encaixe peças geométricas no grid 10x10 para limpar linhas e colunas completas simultaneamente, ativando combos explosivos e dobrando seus pontos no ranking.",
    category: "Puzzle",
    tags: ["Puzzle", "Raciocínio", "Grid 10x10", "Combos", "Habilidade"],
    primary_color: "#00F0FF",
    play_url: "https://blockerino-play.vercel.app/",
    status: "active",
    campaigns_count: 1,
    created_at: "2026-08-05T10:00:00Z",
    updated_at: "2026-09-08T14:00:00Z",
  },
  {
    id: "game-bubbles-cash",
    name: "Bubble Cash",
    slug: "bubbles-cash",
    logo_url: "https://bubblecash-platform.vercel.app/og.png",
    thumbnail_url: "https://bubblecash-platform.vercel.app/og.png",
    banner_url: "https://bubblecash-platform.vercel.app/og.png",
    description: "O mais dinâmico bubble shooter de mira e precisão. Conecte bolhas da mesma cor, limpe o tabuleiro em velocidade recorde e dispute o topo do ranking de premiação!",
    how_it_works: "Mire e dispare bolhas da mesma cor para estourar aglomerados e limpar o teto. Todos os competidores recebem o mesmo tabuleiro, premiando agilidade motora e estratégia.",
    category: "Habilidade",
    tags: ["Habilidade", "Torneio", "Bubble Shooter", "Agilidade", "PIX"],
    primary_color: "#a855f7",
    play_url: "https://bubblecash-platform.vercel.app/",
    status: "active",
    campaigns_count: 1,
    created_at: "2026-08-01T10:00:00Z",
    updated_at: "2026-09-10T12:00:00Z",
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-fruit-cash-fatia-pix",
    title: "Fruit Cash: Cortou Frutinha, Sacou PIX",
    slug: "fruit-cash-fatia-pix",
    game_id: "game-fruit-cash",
    game_name: "Fruit Cash",
    game_slug: "fruit-cash",
    game_color: "#22c55e",
    game_thumbnail: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&auto=format&fit=crop&q=80",
    banner_url: "https://fruitcash-fun.vercel.app/imagens/og-banner.jpg",
    description: "Divulgue o jogo da frutinha mais quente do Brasil! Mostre sua agilidade fatiando frutas, desviando de bombas e ativando saques imediatos via PIX com 100% de bônus.",
    benefits: [
      "Cache garantido por conversão qualificada",
      "+600 XP no Creator Hub",
      "Destaque na aba de Top Creators",
      "Bônus especial de 100% no primeiro depósito para seus seguidores",
    ],
    instructions: "Siga o passo a passo com atenção. Mostre que é jogo de reflexo e habilidade, corte frutas nos stories e deixe seu link de convite oficial com o bônus de 100%!",
    status: "active",
    min_level: 1,
    max_creators: 150,
    active_creators_count: 52,
    sequential_progression: true,
    xp_total: 600,
    start_date: "2026-09-01T00:00:00Z",
    end_date: "2026-10-15T23:59:59Z",
    missions: [
      {
        id: "m-fc-1",
        campaign_id: "camp-fruit-cash-fatia-pix",
        step_order: 1,
        title: "Testar o Game na Demo ou Valendo",
        description: "Acesse https://fruitcash-fun.vercel.app/, jogue algumas partidas e pegue a manha de fatiar combos rápidos sem tocar nas bombas.",
        requirements: ["Confirmar acesso ao jogo", "Print da tela inicial ou jogando"],
        xp_reward: 100,
        upload_type: "image",
        deadline_days: 2,
      },
      {
        id: "m-fc-2",
        campaign_id: "camp-fruit-cash-fatia-pix",
        step_order: 2,
        title: "Print do Jogo ou Stories no Ar",
        description: "Não precisa enviar vídeo! Só tirar um print nítido do seu gameplay cortando frutas ou do story publicado com seu link de convite oficial.",
        requirements: ["Print nítido do jogo ou story", "Link de afiliado visível", "Sem tapar a pontuação"],
        xp_reward: 200,
        upload_type: "image",
        deadline_days: 3,
      },
      {
        id: "m-fc-3",
        campaign_id: "camp-fruit-cash-fatia-pix",
        step_order: 3,
        title: "Print dos Stories com Link do Bônus",
        description: "Solte sequência nos stories convidando a galera com a figurinha de link para dobrar o depósito e envie o print da postagem no ar.",
        requirements: ["Print dos stories ativos com a figurinha de link", "Destacar bônus de 100% no primeiro depósito", "Manter visível 24h"],
        xp_reward: 150,
        upload_type: "image",
        deadline_days: 3,
      },
      {
        id: "m-fc-4",
        campaign_id: "camp-fruit-cash-fatia-pix",
        step_order: 4,
        title: "Print dos Insights do Story",
        description: "Envie um print nítido do painel profissional com alcance e número de cliques no sticker após 24h.",
        requirements: ["Print das métricas após 24h", "Cliques e alcance legíveis"],
        xp_reward: 150,
        upload_type: "image",
        deadline_days: 2,
      },
    ],
    created_at: "2026-09-01T12:00:00Z",
  },
  {
    id: "camp-krs777-vip-cassino",
    title: "KRS 777: Slots, Mines & Fortuna VIP",
    slug: "krs777-vip-cassino",
    game_id: "game-krs-777",
    game_name: "KRS 777 (Casino Online)",
    game_slug: "krs-777",
    game_color: "#fbbf24",
    game_thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80",
    banner_url: "https://krs777.online/assets/images/krs777_share_banner.jpg",
    description: "Apresente o cassino mais completo da internet para seu público com bônus de boas-vindas a partir de R$ 20 e os melhores slots do momento: Fortune Tiger e Mines!",
    benefits: [
      "Comissões agressivas por depósito e faturamento",
      "+750 XP no Creator Hub",
      "Badge de Criador High Roller",
      "Roteiros prontos testados e validados para alta conversão",
    ],
    instructions: "Apresente os diferenciais da KRS 777: saque imediato via PIX, suporte 24h e jogos mais buscados. Divulgue responsavelmente para maiores de 18 anos.",
    status: "active",
    min_level: 2,
    max_creators: 100,
    active_creators_count: 38,
    sequential_progression: true,
    xp_total: 750,
    start_date: "2026-09-02T00:00:00Z",
    end_date: "2026-10-31T23:59:59Z",
    missions: [
      {
        id: "m-krs-1",
        campaign_id: "camp-krs777-vip-cassino",
        step_order: 1,
        title: "Acessar o Lobby da KRS 777",
        description: "Visite https://krs777.online/, conheça os slots disponíveis (Fortune Tiger, Mines) e o fluxo do PIX.",
        requirements: ["Criar conta de creator", "Print do lobby ou conta logada"],
        xp_reward: 150,
        upload_type: "image",
        deadline_days: 2,
      },
      {
        id: "m-krs-2",
        campaign_id: "camp-krs777-vip-cassino",
        step_order: 2,
        title: "Print dos Stories Apresentando o Bônus",
        description: "Não precisa enviar vídeo! Só mandar print dos stories ativos com a figurinha de link destacando os bônus da KRS 777.",
        requirements: ["Print do story com sticker de link visível", "Aviso obrigatório +18"],
        xp_reward: 300,
        upload_type: "image",
        deadline_days: 3,
      },
      {
        id: "m-krs-3",
        campaign_id: "camp-krs777-vip-cassino",
        step_order: 3,
        title: "Divulgar Link em Canal Telegram ou Bio",
        description: "Compartilhe o link da KRS 777 com call to action claro no seu canal de avisos ou no perfil e envie o print da publicação.",
        requirements: ["Print da publicação ou bio com o link ativo", "Link funcionando perfeitamente"],
        xp_reward: 150,
        upload_type: "image",
        deadline_days: 3,
      },
      {
        id: "m-krs-4",
        campaign_id: "camp-krs777-vip-cassino",
        step_order: 4,
        title: "Print de Conversões e Cliques",
        description: "Envie print das métricas de cliques gerados no seu link de indicação.",
        requirements: ["Print do painel de cliques", "Dados legíveis"],
        xp_reward: 150,
        upload_type: "image",
        deadline_days: 2,
      },
    ],
    created_at: "2026-09-02T14:00:00Z",
  },
  {
    id: "camp-bubbles-cash-setembro",
    title: "Bubbles Cash: Desafio de Lançamento",
    slug: "bubbles-cash-setembro",
    game_id: "game-bubbles-cash",
    game_name: "Bubble Cash",
    game_slug: "bubbles-cash",
    game_color: "#00F59B",
    game_thumbnail: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80",
    description: "Campanha de alta performance focada em divulgar a nova mecânica de torneios de habilidade do Bubbles Cash no Instagram Stories e Reels.",
    benefits: [
      "Cache prioritário por entrega validada",
      "+500 XP no Creator Hub",
      "Destaque no Hall da Fama dos Creators",
      "Acesso antecipado aos próximos lançamentos",
    ],
    instructions: "Siga o passo a passo com atenção. Cada etapa deve ser submetida e aprovada antes da próxima. Seja autêntico ao demonstrar a habilidade no jogo!",
    status: "active",
    min_level: 1,
    max_creators: 100,
    active_creators_count: 34,
    sequential_progression: true,
    xp_total: 500,
    start_date: "2026-09-01T00:00:00Z",
    end_date: "2026-09-30T23:59:59Z",
    missions: [
      {
        id: "m-bc-1",
        campaign_id: "camp-bubbles-cash-setembro",
        step_order: 1,
        title: "Instalar & Testar o Game",
        description: "Abra o game pelo link oficial, jogue 2 ou 3 partidas pra pegar a manha dos combos e envie o print da tela de início.",
        requirements: ["Print da tela do jogo aberta"],
        xp_reward: 50,
        upload_type: "image",
        deadline_days: 2,
      },
      {
        id: "m-bc-2",
        campaign_id: "camp-bubbles-cash-setembro",
        step_order: 2,
        title: "Print do Gameplay e Pontuação",
        description: "Não precisa enviar vídeo! Só mandar print da sua tela com a pontuação e combos reais no Bubbles Cash.",
        requirements: ["Print com pontuação nítida", "Sem elementos que tapem a pontuação"],
        xp_reward: 150,
        upload_type: "image",
        deadline_days: 3,
      },
      {
        id: "m-bc-3",
        campaign_id: "camp-bubbles-cash-setembro",
        step_order: 3,
        title: "Print dos Stories com Link Oficial",
        description: "Posta Stories mostrando o jogo e convidando seus seguidores com a figurinha de link. Envie o print do story no ar.",
        requirements: ["Print do Story com link de download visível", "Manter visível por 24h"],
        xp_reward: 100,
        upload_type: "image",
        deadline_days: 3,
      },
      {
        id: "m-bc-4",
        campaign_id: "camp-bubbles-cash-setembro",
        step_order: 4,
        title: "Print dos Resultados e Alcance",
        description: "Tira um print dos insights do Story após 24h pra gente ver o alcance e cliques da galera.",
        requirements: ["Print nítido do painel profissional do Instagram", "Comprovar quantidade de cliques no sticker"],
        xp_reward: 100,
        upload_type: "image",
        deadline_days: 2,
      },
      {
        id: "m-bc-5",
        campaign_id: "camp-bubbles-cash-setembro",
        step_order: 5,
        title: "Mandar Aquele Feedback Sincero",
        description: "Manda um breve relato ou print com a reação da sua comunidade contando o que acharam do jogo!",
        requirements: ["Opinião sincera e construtiva", "Pontos altos de diversão e sugestões"],
        xp_reward: 100,
        upload_type: "document",
        deadline_days: 2,
      },
    ],
    created_at: "2026-09-01T12:00:00Z",
  },
  {
    id: "camp-blockerino-record",
    title: "Blockerino: Mestre dos Blocos",
    slug: "blockerino-mestre-dos-blocos",
    game_id: "game-blockerino",
    game_name: "Blockerino",
    game_slug: "blockerino",
    game_color: "#00F0FF",
    game_thumbnail: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80",
    banner_url: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80",
    description: "Desafie sua audiência a bater o seu recorde no Blockerino através de um post, Reel ou stories com seu link de afiliado.",
    benefits: [
      "+400 XP no Creator Hub",
      "Badge exclusiva 'Arquiteto do Grid'",
      "Bônus por visualizações qualificadas",
    ],
    instructions: "Compartilhe sua pontuação e mande o print para validar.",
    status: "active",
    min_level: 2,
    max_creators: 50,
    active_creators_count: 18,
    sequential_progression: true,
    xp_total: 400,
    start_date: "2026-09-05T00:00:00Z",
    end_date: "2026-10-05T23:59:59Z",
    missions: [
      {
        id: "m-bw-1",
        campaign_id: "camp-blockerino-record",
        step_order: 1,
        title: "Print do Desafio com Link Oficial",
        description: "Não precisa enviar vídeo! Publique seu desafio do Blockerino com o link oficial nos Stories ou feed e envie o print da publicação.",
        requirements: ["Print da publicação com o link oficial", "Uso da hashtag #KRSBlockerino"],
        xp_reward: 200,
        upload_type: "image",
        deadline_days: 4,
      },
      {
        id: "m-bw-2",
        campaign_id: "camp-blockerino-record",
        step_order: 2,
        title: "Print de Métricas do Conteúdo",
        description: "Manda print dos insights do post/story depois de 24h a 48h no ar.",
        requirements: ["Print da aba de insights do conteúdo com métricas legíveis"],
        xp_reward: 200,
        upload_type: "image",
        deadline_days: 3,
      },
    ],
    created_at: "2026-09-05T14:00:00Z",
  },
];

export const SEED_LEVELS: LevelConfig[] = [
  {
    level: 1,
    name: "Starter",
    min_xp: 0,
    color: "#94A3B8",
    icon_name: "Sparkles",
    badge_title: "Novo Criador",
    unlocked_perks: ["Acesso às campanhas iniciais", "Download da Central de Criativos"],
  },
  {
    level: 2,
    name: "Creator",
    min_xp: 250,
    color: "#38BDF8",
    icon_name: "Flame",
    badge_title: "Criador Ativo",
    unlocked_perks: ["Desbloqueio de campanhas nível 2", "Participação no ranking mensal"],
  },
  {
    level: 3,
    name: "Creator Plus",
    min_xp: 750,
    color: "#00F59B",
    icon_name: "Zap",
    badge_title: "Criador em Ascensão",
    unlocked_perks: ["Aprovação prioritária em até 12 horas", "Badge no perfil público"],
  },
  {
    level: 4,
    name: "Creator Pro",
    min_xp: 1500,
    color: "#F59E0B",
    icon_name: "Award",
    badge_title: "Especialista em Jogos",
    unlocked_perks: ["Campanhas exclusivas com maior remuneração", "Suporte direto via WhatsApp VIP"],
  },
  {
    level: 5,
    name: "Creator Elite",
    min_xp: 2400,
    color: "#8B5CF6",
    icon_name: "Crown",
    badge_title: "Elite KRS",
    unlocked_perks: ["Multiplicador de XP 1.25x", "Acesso aos testes beta de novos jogos"],
  },
  {
    level: 6,
    name: "VIP Legend",
    min_xp: 4000,
    color: "#EC4899",
    icon_name: "Gem",
    badge_title: "Lenda dos Torneios",
    unlocked_perks: ["Multiplicador 1.5x", "Convites para eventos e lançamentos presenciais"],
  },
];

export const SEED_BADGES: Badge[] = [
  {
    id: "badge-primeira-campanha",
    name: "Primeira Campanha",
    slug: "primeira-campanha",
    description: "Completou com sucesso a primeira campanha de jogo por habilidade.",
    icon_name: "Trophy",
    rarity: "common",
    xp_value: 100,
    target_role: "INFLUENCER",
    criteria_description: "Entregar todas as missões da primeira campanha.",
  },
  {
    id: "badge-5-campanhas",
    name: "5 Campanhas",
    slug: "5-campanhas",
    description: "Finalizou 5 campanhas demonstrando consistência de produção.",
    icon_name: "Layers",
    rarity: "rare",
    xp_value: 250,
    target_role: "INFLUENCER",
    criteria_description: "Concluir 5 campanhas distintas aprovadas.",
  },
  {
    id: "badge-entrega-perfeita",
    name: "Entrega Perfeita",
    slug: "entrega-perfeita",
    description: "Teve material aprovado de primeira sem necessidade de alterações.",
    icon_name: "CheckCircle2",
    rarity: "rare",
    xp_value: 150,
    target_role: "INFLUENCER",
    criteria_description: "3 submissões seguidas aprovadas sem ajustes.",
  },
  {
    id: "badge-creator-consistente",
    name: "Creator Consistente",
    slug: "creator-consistente",
    description: "Manteve sequência de atividade profissional por 4 semanas consecutivas.",
    icon_name: "Flame",
    rarity: "epic",
    xp_value: 300,
    target_role: "INFLUENCER",
    criteria_description: "Streak profissional de pelo menos 4 semanas.",
  },
  {
    id: "badge-creator-elite",
    name: "Creator Elite",
    slug: "creator-elite",
    description: "Alcançou o Nível 5 no ecossistema KRS Creator Hub.",
    icon_name: "Crown",
    rarity: "legendary",
    xp_value: 500,
    target_role: "INFLUENCER",
    criteria_description: "Atingir 2.400 XP no Creator Hub.",
  },
  {
    id: "badge-captador-destaque",
    name: "Captador Destaque",
    slug: "captador-destaque",
    description: "Trouxe criadores com alta taxa de engajamento e conclusão de campanhas.",
    icon_name: "Users",
    rarity: "epic",
    xp_value: 350,
    target_role: "CAPTADOR",
    criteria_description: "Captar 5 influencers que completaram campanhas.",
  },
  {
    id: "badge-primeiro-captado",
    name: "Primeiro Influencer",
    slug: "primeiro-influencer",
    description: "Cadastrou o primeiro criador de conteúdo na sua rede.",
    icon_name: "UserPlus",
    rarity: "common",
    xp_value: 100,
    target_role: "CAPTADOR",
    criteria_description: "Primeira indicação com cadastro concluído.",
  },
  {
    id: "badge-30-dias-ativo",
    name: "30 Dias Ativo",
    slug: "30-dias-ativo",
    description: "Presença e produtividade contínua no KRS Creator Hub.",
    icon_name: "Calendar",
    rarity: "epic",
    xp_value: 300,
    target_role: "ALL",
    criteria_description: "Atividade na plataforma por 30 dias.",
  },
];

export const SEED_XP_EVENTS: XPEventConfig[] = [
  { id: "xp-1", event_key: "profile_completed", description: "Completar Onboarding e Perfil", xp_amount: 50, is_active: true },
  { id: "xp-2", event_key: "campaign_joined", description: "Escolher e Iniciar Campanha", xp_amount: 25, is_active: true },
  { id: "xp-3", event_key: "story_published", description: "Publicar Story Oficial", xp_amount: 100, is_active: true },
  { id: "xp-4", event_key: "material_submitted", description: "Enviar Material de Missão", xp_amount: 100, is_active: true },
  { id: "xp-5", event_key: "gameplay_approved", description: "Gameplay Aprovado", xp_amount: 150, is_active: true },
  { id: "xp-6", event_key: "campaign_completed", description: "Concluir Campanha Completa", xp_amount: 500, is_active: true },
  { id: "xp-7", event_key: "on_time_bonus", description: "Entregar Dentro do Prazo", xp_amount: 100, is_active: true },
  { id: "xp-8", event_key: "weekly_streak", description: "Sequência Semanal Ativa", xp_amount: 200, is_active: true },
  { id: "xp-9", event_key: "referral_completed", description: "Influencer Indicado Concluiu Campanha", xp_amount: 300, is_active: true },
];

export const SEED_CREATOR_PASS: CreatorPassSeason = {
  id: "season-1-genesis",
  number: 1,
  name: "Temporada 1: Cyber Genesis",
  theme: "O início da nova era dos jogos de habilidade",
  banner_url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80",
  start_date: "2026-09-01T00:00:00Z",
  end_date: "2026-09-30T23:59:59Z",
  days_left: 14,
  rewards: [
    { level: 1, xp_required: 100, title: "Badge Genesis Starter", description: "Distintivo comemorativo da temporada inaugural", type: "badge", is_elite_tier: false, reward_icon: "Shield" },
    { level: 2, xp_required: 300, title: "Pacote de Banners 4K", description: "Artes exclusivas em alta resolução para Stories", type: "exclusive_material", is_elite_tier: false, reward_icon: "Download" },
    { level: 3, xp_required: 600, title: "Fila Rápida de Aprovação", description: "Suas entregas são analisadas antes de 12 horas", type: "priority_review", is_elite_tier: false, reward_icon: "Zap" },
    { level: 4, xp_required: 1000, title: "Multiplicador de XP 1.1x", description: "Gere 10% a mais de XP em todas as missões", type: "multiplier", is_elite_tier: true, reward_icon: "Sparkles" },
    { level: 5, xp_required: 1500, title: "Acesso Campanha VIP Fruit Cash", description: "Desbloqueia campanha fechada com bônus especial", type: "special_campaign", is_elite_tier: false, reward_icon: "Lock" },
    { level: 6, xp_required: 2100, title: "Selo Creator Gold no Perfil", description: "Ícone dourado de notoriedade na plataforma", type: "badge", is_elite_tier: true, reward_icon: "Award" },
    { level: 7, xp_required: 2800, title: "Roteiro Customizado Exclusivo", description: "Roteiro individual criado pelo time de copy da KRS", type: "exclusive_material", is_elite_tier: false, reward_icon: "FileText" },
    { level: 8, xp_required: 3600, title: "Multiplicador de XP 1.25x", description: "Impulso de 25% na pontuação da temporada", type: "multiplier", is_elite_tier: true, reward_icon: "Flame" },
    { level: 9, xp_required: 4500, title: "Kit Creator Merch Físico", description: "Moletom + Boné oficial KRS Creator", type: "exclusive_material", is_elite_tier: true, reward_icon: "Gift" },
    { level: 10, xp_required: 5500, title: "Troféu Digital & Badge Genesis Lord", description: "Reconhecimento máximo da Season 1", type: "badge", is_elite_tier: true, reward_icon: "Crown" },
  ],
};

export const SEED_SCRIPTS: ScriptTemplate[] = [
  {
    id: "script-story-1",
    title: "Roteiro Dinâmico para Stories (Bubbles Cash)",
    game_id: "game-bubbles-cash",
    game_name: "Bubbles Cash",
    category: "story",
    content: "Fala galera! Muita gente me pergunta quais jogos eu realmente jogo quando quero um desafio de verdade. Conheci o Bubbles Cash, que é 100% focado em habilidade: todo mundo joga com o exato mesmo tabuleiro e vence quem tiver mais reflexo e estratégia. Se liga nesse gameplay que acabei de gravar!",
    call_to_action: "Arrasta pra cima ou clica no link abaixo pra baixar e me desafiar!",
    tips: [
      "Grave em ambiente bem iluminado",
      "Mostre o celular com o jogo aberto nos primeiros 3 segundos",
      "Insira o sticker de link no centro inferior da tela",
    ],
    duration_estimate: "30-45 segundos (2 a 3 stories)",
  },
  {
    id: "script-reel-1",
    title: "Hook Rápido de 3 Segundos para TikTok / Reels",
    game_id: "game-blockerino",
    game_name: "Blockerino",
    category: "reel_tiktok",
    content: "'Se você acha que tem raciocínio rápido, duvido você bater 5.000 pontos nesse jogo...' [Corta imediatamente para você encaixando a peça final do combo no Blockerino com som vibrante]. Mostre sua reação no final surpreso com o recorde.",
    call_to_action: "O link oficial tá na minha bio. Quem conseguir mais pontos me marca que eu vou repostar!",
    tips: [
      "Comece o vídeo direto com o corte rápido da jogada",
      "Use legendas em fonte destacada",
      "Adicione áudio em alta no momento da postagem",
    ],
    duration_estimate: "15-20 segundos",
  },
  {
    id: "script-legend-1",
    title: "Legenda Pronta com Copy Persuasiva",
    game_id: "game-bubbles-cash",
    game_name: "Bubbles Cash",
    category: "caption_legend",
    content: "Quem aí curte jogos onde a vitória depende unicamente da sua habilidade e raciocínio? 🎯\n\nTestei o @BubblesCash e o ritmo das partidas é insano. Todos os jogadores competem com as mesmas peças e vence a melhor estratégia de combos.\n\n👉 Baixe pelo link na bio ou nos Stories e teste seus reflexos!",
    call_to_action: "Clique no link da bio e entre no desafio!",
    tips: ["Adicione 3 a 5 hashtags relevantes como #jogosdehabilidade #gamesmobile #bubblescash"],
    duration_estimate: "Texto para copiar",
  },
];

export const SEED_CREATIVE_ASSETS: CreativeAsset[] = [
  {
    id: "asset-1",
    title: "Bubbles Cash - Logo Oficial PNG Transparente",
    game_id: "game-bubbles-cash",
    game_name: "Bubbles Cash",
    type: "logo",
    file_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    preview_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
    file_size: "1.4 MB",
    tags: ["Logo", "PNG", "Transparente", "HD"],
    created_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "asset-2",
    title: "Template de Story 9:16 com Moldura Neon",
    game_id: "game-bubbles-cash",
    game_name: "Bubbles Cash",
    type: "story_template",
    file_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1080&auto=format&fit=crop&q=80",
    preview_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=300&auto=format&fit=crop&q=80",
    file_size: "4.8 MB",
    tags: ["Stories", "Moldura", "Instagram"],
    created_at: "2026-09-02T11:00:00Z",
  },
  {
    id: "asset-3",
    title: "Blockerino - Banner Promocional Horizontal",
    game_id: "game-blockerino",
    game_name: "Blockerino",
    type: "banner",
    file_url: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop&q=80",
    preview_url: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=400&auto=format&fit=crop&q=80",
    file_size: "3.2 MB",
    tags: ["Banner", "Feed", "Horizontal"],
    created_at: "2026-09-04T12:00:00Z",
  },
  {
    id: "asset-4",
    title: "Guia PDF de Boas Práticas para Criadores",
    type: "guide_pdf",
    file_url: "#",
    preview_url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=300&auto=format&fit=crop&q=80",
    file_size: "2.1 MB",
    tags: ["Manual", "PDF", "Diretrizes", "LGPD"],
    created_at: "2026-09-01T09:00:00Z",
  },
];

export const DEMO_CREATOR: CreatorProfile = {
  id: "user-creator-1",
  email: "afiliado@krscreatorhub.com",
  name: "Creator Afiliado",
  username: "afiliado",
  avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80",
  phone: "+55 (11) 98765-4321",
  city: "São Paulo",
  state: "SP",
  role: "INFLUENCER",
  onboarding_completed: true,
  niches: ["Gaming", "Jogos por Habilidade", "Entretenimento"],
  social_accounts: [
    {
      platform: "instagram",
      username: "afiliado_krs",
      url: "https://instagram.com/",
      followers: 0,
      avg_views: 0,
      engagement_rate: 0,
    },
  ],
  campaign_preferences: ["Jogos de Habilidade", "Puzzle", "Cassino"],
  current_xp: 0,
  current_level: 1,
  streak_weeks: 0,
  completed_campaigns_count: 0,
  approved_submissions_count: 0,
  wallet_balance: 0.00,
  is_affiliate: true,
  affiliate_code: "afiliado",
  created_at: "2026-09-01T10:00:00Z",
  updated_at: "2026-09-24T00:00:00Z",
};

export const DEMO_CAPTADOR: CaptadorProfile = {
  id: "user-captador-1",
  email: "marcos.captador@krscreatorhub.com",
  name: "Marcos Vinicius",
  username: "marcos_captador",
  avatar_url: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&auto=format&fit=crop&q=80",
  phone: "+55 (21) 99887-6543",
  city: "Rio de Janeiro",
  state: "RJ",
  role: "CAPTADOR",
  onboarding_completed: true,
  referral_code: "MARCOS10",
  current_xp: 0,
  current_level: 1,
  streak_weeks: 0,
  total_referred: 0,
  active_creators: 0,
  campaigns_completed_by_referred: 0,
  wallet_balance: 0.00,
  created_at: "2026-07-20T10:00:00Z",
  updated_at: "2026-09-24T00:00:00Z",
};

export const DEMO_ADMIN: UserProfile = {
  id: "user-admin-1",
  email: "admin@krscreatorhub.com",
  name: "KRS Operations Master",
  username: "krs_admin",
  avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
  phone: "+55 (11) 91234-5678",
  city: "São Paulo",
  state: "SP",
  role: "ADMIN",
  onboarding_completed: true,
  wallet_balance: 98500.00,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-09-15T20:00:00Z",
};

export const SEED_SUBMISSIONS: Submission[] = [];

export const INITIAL_SETTINGS: PlatformSettings = {
  platform_name: "KRS CREATOR HUB",
  primary_color: "#00F59B",
  support_whatsapp: "+5511999999999",
  support_email: "contato@krscreatorhub.com",
  terms_url: "/termos",
  privacy_url: "/privacidade",
  rules_version: "1.0.0",
  maintenance_mode: false,
  allow_new_registrations: true,
};

export const SEED_AFFILIATE_STATS: GameAffiliateStats[] = [
  {
    game_id: "game-fruit-cash",
    game_name: "Fruit Cash",
    game_slug: "fruit-cash",
    category: "Habilidade",
    primary_color: "#22c55e",
    logo_url: "https://fruitcash-fun.vercel.app/imagens/asset_2.png",
    thumbnail_url: "https://fruitcash-fun.vercel.app/imagens/og-banner.jpg",
    referral_param: "ref",
    referral_url: "https://fruitcash-fun.vercel.app/?ref=afiliado",
    clicks: 0,
    signups: 0,
    deposits_count: 0,
    total_deposited: 0.00,
    commission_earned: 0.00,
    available_balance: 0.00,
    commission_rate: "20% RevShare + R$ 10 CPA",
  },
  {
    game_id: "game-krs-777",
    game_name: "KRS 777 (Casino Online)",
    game_slug: "krs-777",
    category: "Cassino",
    primary_color: "#fbbf24",
    logo_url: "https://krs777.online/storage/krs777_favicon.png",
    thumbnail_url: "https://krs777.online/assets/images/krs777_share_banner.jpg",
    referral_param: "r",
    referral_url: "https://krs777.online/?r=afiliado",
    clicks: 0,
    signups: 0,
    deposits_count: 0,
    total_deposited: 0.00,
    commission_earned: 0.00,
    available_balance: 0.00,
    commission_rate: "30% RevShare + R$ 15 FTD",
  },
  {
    game_id: "game-blockerino",
    game_name: "Blockerino",
    game_slug: "blockerino",
    category: "Puzzle",
    primary_color: "#00F0FF",
    logo_url: "https://blockerino-play.vercel.app/og.png",
    thumbnail_url: "https://blockerino-play.vercel.app/og.png",
    referral_param: "ref",
    referral_url: "https://blockerino-play.vercel.app/?ref=afiliado",
    clicks: 0,
    signups: 0,
    deposits_count: 0,
    total_deposited: 0.00,
    commission_earned: 0.00,
    available_balance: 0.00,
    commission_rate: "15% por torneio disputado",
  },
  {
    game_id: "game-bubbles-cash",
    game_name: "Bubble Cash",
    game_slug: "bubbles-cash",
    category: "Habilidade",
    primary_color: "#a855f7",
    logo_url: "https://bubblecash-platform.vercel.app/og.png",
    thumbnail_url: "https://bubblecash-platform.vercel.app/og.png",
    referral_param: "ref",
    referral_url: "https://bubblecash-platform.vercel.app/?ref=afiliado",
    clicks: 0,
    signups: 0,
    deposits_count: 0,
    total_deposited: 0.00,
    commission_earned: 0.00,
    available_balance: 0.00,
    commission_rate: "15% por premiação líquida",
  },
];

export const SEED_AFFILIATE_CONVERSIONS: AffiliateConversionRecord[] = [];

